estiam_blog:
    resource: "@EstiamBlogBundle/Controller/"
    type:     annotation
    prefix:   /%locale%

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
    prefix: /%locale%
